version: "3.9"

services:
  db:
    image: postgres:16
    container_name: pg-foodgram
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodgram
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
