"""add users table (fix template)

Revision ID: f82cfd21abe9
Revises: 514f5ec3e8f2
Create Date: 2025-10-25 15:24:18.207407
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f82cfd21abe9"
down_revision = "514f5ec3e8f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=200), nullable=True),
        sa.Column("last_name", sa.String(length=200), nullable=True),
        sa.Column("username", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users__email")),
        sa.UniqueConstraint("username", name=op.f("uq_users__username")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
